name: ✅ Validate Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: validate-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    if: github.repository != 'community-owned-workshop/scrap-mechanic-template' # disable action for template repo; you can remove this line in your own repo
    uses: community-owned-workshop/steam-workshop-devops/.github/workflows/validate-scrap-mechanic.yml@feature/scrap-mechanic
